trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Run tests'

- script: |
    npm install
    npm test
  displayName: 'npm install and test'
