name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: run
        run: |
          npm install
          npm test
